displayName: Traefik unleash plugin

type: middleware

import: github.com/traefik/unleash

summary: Allow to rewrite host path and headers from request under a feature flag toggle from Unleash.

iconPath: .assets/unleash_logo.png
bannerPath: .assets/unleash_banner.png

testData:
  url: "http://unleash:4242/api/"
  app: "test-app"
  interval: 10
  metrics:
    interval: 10
  toggles:
    - feature: "test-toggle-path"
      path:
        value: "/foo"
        rewrite: "/bar"