http:
  serversTransports:
    default:
      insecureSkipVerify: true
  services:
    unleash:
      loadBalancer:
        servers:
          - url: "http://whoami1"
        passHostHeader: true
        serversTransport: default
  routers:
    unleash:
      rule: "Host(`localhost`)"
      entryPoints:
        - web
      middlewares:
        - unleash
      service: unleash
  middlewares:
    unleash:
      plugin:
        unleash:
          url: "http://unleash:4242/api/"
          app: "test-app"
          interval: 10
          metrics:
            interval: 10
          toggles:
            - feature: "test-toggle-user-id"
              pathRewrite:
                pathMatcher: "/foo"
                rewriteRule: "/bar"
              hostRewrite:
                hostMatcher: "localhost"
                rewriteRule: "whoami2"
              headerModifiers:
                - headerName: "X-Foo"
                  headerValue: "Bar"
                  context: "request"
                - headerName: "X-Served-By"
                  headerValue: "whoami2"
                  context: "response"
            - feature: "test-toggle"
              pathRewrite:
                pathMatcher: "/bar"
                rewriteRule: "/foo"
              hostRewrite:
                hostMatcher: "localhost"
                rewriteRule: "whoami2"
            - feature: "test-toggle-path"
              pathRewrite:
                pathMatcher: "/john"
                rewriteRule: "/doe"
            - feature: "test-toggle-flexible-rollout-100"
              pathRewrite:
                pathMatcher: "/hello"
                rewriteRule: "/world"
            - feature: "test-toggle-flexible-rollout-0"
              pathRewrite:
                pathMatcher: "/alice"
                rewriteRule: "/bob"
            - feature: "test-toggle-host"
              hostRewrite:
                hostMatcher: "localhost"
                rewriteRule: "whoami1"