entryPoints:
  web:
    address: ":80"

api:
  dashboard: true
  insecure: true


providers:
  file:
    filename: "/etc/traefik/dynamic.yml"

log:
  level: TRACE

experimental:
  localPlugins:
    unleash:
      moduleName: "github.com/amj1985/traefik-unleash-plugin"
